[target.'cfg(target_os = "windows")']
#rustflags = ["-C", "link-args=/entry:main /SUBSYSTEM:CONSOLE"]
#rustflags = ["-C", "link-args=-nostartfiles"]
#rustflags = ["-C", "target-feature=-crt-static"]

[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-args=-nostartfiles"]



